[package]
name = "fake_firmware_process"
description = "Simple process which just sleep for 10 hours. Used for work purposes to emulate firmware."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
